// The README is generated too, so the numbers in the prose can never drift
// from the numbers in the pictures.

import { towersMarkdown } from './scenes/towers.mjs'
import { VENTURES } from './data/ventures.mjs'
import { byMonth } from './lib/data.mjs'

const band = (file, alt) => `<img src="assets/gen/${file}.svg" alt="${alt}" width="100%">`

export function readme(d, tiles, geojson) {
  const months = byMonth(d.days)
  const first = months.find((m) => m.total > 0)
  const last = months[months.length - 1]

  return `<!--
  This file is generated. Do not edit it by hand.

  The world is drawn by engine/ and rebuilt every day by
  .github/workflows/build-world.yml, so every number below is live.

    node engine/build.mjs      rebuild the bands and this file
    node engine/shot.mjs       render them in Chromium, both themes
-->

${band('01-hero', 'Rodrigo Casanova-Aleman, builder. A night skyline under El Avila.')}

${towersMarkdown(tiles)}

${band('03-propiedash', 'Propiedash, the real-estate marketplace for Venezuela')}

${band('04-opennodo', 'OpenNodo, an open place standard for Venezuela, 2,870 places')}

<details>
<summary><b>Open the live map</b> &nbsp;·&nbsp; every OpenNodo federal entity, pan and zoom it</summary>

<br>

Rendered by GitHub from the [OpenNodo](https://opennodo.org) seed pack. Each marker is a
federal entity; the counts are the municipalities and parishes OpenNodo has records for.

\`\`\`geojson
${geojson}
\`\`\`

</details>

${band('05-studio', 'casanovaaleman studio and the rest of the work')}

${band('06-city', `The year as a city. ${d.total.toLocaleString('en-US')} contributions, one building per day.`)}

${band('07-charts', 'Contributions by month and weekday, drawn in ordered dither')}

${band('08-footer', 'Get in touch')}

<details>
<summary>Read this profile as text</summary>

<br>

**Rodrigo Casanova-Aleman.** I build things. All of them. Caracas, Madrid, Miami, Gainesville.

${VENTURES.map((v) => `- **${v.display}** — ${v.tagline}. ${v.role}. ${linkOf(v)}`).join('\n')}

**The year in numbers.** ${d.total.toLocaleString('en-US')} contributions between ${d.from} and ${d.to},
across ${d.activeDays} days I actually shipped on. Longest streak ${d.longestStreak} days.
Biggest single day ${d.max}. It went from ${first ? first.total : 0} in
${first ? first.month : 'the start'} to ${last.total.toLocaleString('en-US')} in ${last.month}.

**About the pictures.** Every band above is an SVG generated by \`engine/\` from live GitHub data and
committed to this repo, so nothing here depends on a third-party image service staying up. They are
theme-aware: the same city, at night on GitHub's dark theme and in daylight on light. There are no
gradients anywhere in this profile — every tonal ramp is an ordered Bayer dither, because the
Propiedash brand does not allow gradients and a dot grid turns out to be a better answer anyway.
The skyline under the hero is seven separate images sitting flush against each other, which is how
each building gets its own link.

</details>
`
}


const linkOf = (v) => (v.href.startsWith('https://github.com') ? 'Private.' : `<${v.href}>`)
